function [U_initial, U_final] = compute_BCs_U(funcs, BCs, gamma)

U_initial = funcs.U(...
    BCs.rho(1), ...
    BCs.u(1), ...
    funcs.E(BCs.rho(1), BCs.p(1), gamma, BCs.u(1)));

U_final = funcs.U(...
    BCs.rho(2), ...
    BCs.u(2), ...
    funcs.E(BCs.rho(2), BCs.p(2), gamma, BCs.u(2)));

end