function [K, B, M, F, xn] = FE_Neumann(L, h, mu0, beta0, sigma0, fun, q1, q2)
% N = L / h - 1 + 2;
% 
% % Diffusione -> K (rigidezza) -> phi_i' * phi_j'
% K = mu0/h * ( ...
%     diag(2 * ones(N, 1)) + ...
%     diag(-1 * ones(N-1, 1), 1) + ...
%     diag(-1 * ones(N-1, 1), -1) ...
%     );
% K(1, 1) = K(1, 1) / 2;
% K(end, end) = K(end, end) / 2;
% 
% % Trasporto -> B (?) -> phi_i' * phi_j
% B = beta0/2 * ( ...
%     diag(0 * ones(N, 1)) + ...
%     diag(1 * ones(N-1, 1), 1) + ...
%     diag(-1* ones(N-1, 1), -1) ...
%     );
% B(1, 1) = beta0/2 * -1;
% B(end, end) = beta0/2 * 1;
% 
% % Reazione -> M (massa) -> phi_i * phi_j
% M = sigma0 * h/6 * ( ...
%     diag(4 * ones(N, 1)) + ...
%     diag(1 * ones(N-1, 1), 1) + ...
%     diag(1 * ones(N-1, 1), -1) ...
%     );
% 
% M(1, 1) = M(1, 1) / 2;
% M(end, end) = M(end, end) / 2;
% 
% % Forzante calcolata con formula del trapezio
% xn = linspace(0, L, N);
% F = [h * fun(xn)]';
% 
% F(1) = F(1) / 2 + q1;
% F(end) = F(end) / 2 + q2;

N = L / h - 1 + 2;

% Diffusione -> K (rigidezza) -> phi_i' * phi_j'
K = mu0/h * ( ...
    diag(2 * ones(N, 1)) + ...
    diag(-1 * ones(N-1, 1), 1) + ...
    diag(-1 * ones(N-1, 1), -1) ...
    );
K(1, 1) = K(1, 1) / 2;
K(end, end) = K(end, end) / 2;

% Trasporto -> B (?) -> phi_i' * phi_j
B = beta0/2 * ( ...
    diag(0 * ones(N, 1)) + ...
    diag(1 * ones(N-1, 1), 1) + ...
    diag(-1* ones(N-1, 1), -1) ...
    );
B(1, 1) = beta0/2 * -1;
B(end, end) = beta0/2 * 1;

% Reazione -> M (massa) -> phi_i * phi_j
M = sigma0 * h/6 * ( ...
    diag(4 * ones(N, 1)) + ...
    diag(1 * ones(N-1, 1), 1) + ...
    diag(1 * ones(N-1, 1), -1) ...
    );

M(1, 1) = M(1, 1) / 2;
M(end, end) = M(end, end) / 2;

% Forzante calcolata con formula del trapezio
xn = linspace(0, L, N);
F = [h * fun(xn)]';

F(1) = F(1) / 2 + q1;
F(end) = F(end) / 2 + q2;


end

